---
title: "Alex Code"
author: "Alex"
date: "1 5 2021"
output: html_document
---
Loading packages
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

Creating plot: total protein in control vs fraction, rep1= blue, rep2= red, rep3= blue
```{r}
library("ggplot2")
library("tidyverse")

Total_Prot_Rotated <- t(Total_Protein_Data)
Total_Prot_Rotated_df <- data.frame(Total_Prot_Rotated)

ggplot(Total_Prot_Rotated_df, aes(x=1:25))+
  geom_line(aes(y=Total_Prot_Rotated_df[,1]),colour="blue", label="Ctrl_Rep_1")+
  geom_line(aes(y=Total_Prot_Rotated_df[,2]), colour="red", label="Ctrl_Rep_2")+
  geom_line(aes(y=Total_Prot_Rotated_df[,3]), colour = "darkgreen", label = "Ctrl_Rep_3")+
  ggtitle("Total protein amount of control repetition in every fraction")+
  xlab("Fraction")+
  ylab("Protein Amount")+
  theme(legend.position = "right")+
  scale_x_continuous(breaks=1:25)
```

Creating plot: total protein in RNAse vs fraction, rep1= blue, rep2= red, rep3= blue

```{r}
ggplot(Total_Prot_Rotated_df, aes(x=1:25))+
  geom_line(aes(y=Total_Prot_Rotated_df[,4]),colour="blue")+
  geom_line(aes(y=Total_Prot_Rotated_df[,5]), colour="red")+
  geom_line(aes(y=Total_Prot_Rotated_df[,6]), colour = "darkgreen")+
  scale_x_continuous(breaks=1:25)+
  ggtitle("Total protein amount of RNAse repetitions in every fraction")+
  ylab("Protein amount")+
  xlab("Fraction")
```
Creating plot: total mean protein in RNAse & Ctrl vs fraction, RNAse = red, Ctrl = blue

```{r}
Total_Prot_Rotated_mean_df <- Total_Prot_Rotated_df %>%
  mutate(mean_Ctrl = rowMeans(Total_Prot_Rotated_df[,1:3]))%>%
  mutate(mean_RNAse = rowMeans(Total_Prot_Rotated_df[,4:6]))
ggplot(Total_Prot_Rotated_mean_df, aes(x=1:25))+
  geom_line(aes(y=Total_Prot_Rotated_mean_df[,7]), color = "blue")+
  geom_line(aes(y=Total_Prot_Rotated_mean_df[,8]), color = "red")+
  ggtitle("Comparison of total protein amount of control and RNAse")+
  xlab("Fraction")+
  ylab("Protein amount")+
  scale_x_continuous(breaks = 1:25)
```


```{r}
barplot(Total_Protein_Sum, ylab = "Protein amount", las = 2, cex.axis=0.5, cex.names=0.8, main = "Total Protein amount of repetitions")
Total_Protein_Sum
```
```{r}
ggplot(Total_Prot_norm_Rotated_df, aes(x=1:25))+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,4]),colour="blue")+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,5]), colour="red")+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,6]), colour = "darkgreen")+
  scale_x_continuous(breaks=1:25)+
  ggtitle("Normalized protein amount of RNAse repetitions in every fraction")+
  ylab("Protein amount")+
  xlab("Fraction")

ggplot(Total_Prot_norm_Rotated_df, aes(x=1:25))+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,1]),colour="blue")+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,2]), colour="red")+
  geom_line(aes(y=Total_Prot_norm_Rotated_df[,3]), colour = "darkgreen")+
  scale_x_continuous(breaks=1:25)+
  ggtitle("Normalized protein amount of control repetitions in every fraction")+
  ylab("Protein amount")+
  xlab("Fraction")
```